name: pdf_toolkit
description: Simple offline PDF toolkit
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  pdf: ^3.11.1
  share_plus: ^10.0.0

flutter:
  uses-material-design: true
